Add book login
wolox-training/jg-angular pull request #10
Opened 2020-04-01 21:21 UTC by JuanGutierrez43

## Summary 

This will add the new login feature. Its a new view that redirects to the index when you press the login button.

**New features**

- Set the form for the login
- Set the buttons with flex.
- Set the inputs.
- Set the Wolox logo over the form. 
- The login button now redirect you to the index, where the book list is. 

## Screenshots 
![Screenshot from 2020-04-01 18-20-11](https://user-images.githubusercontent.com/29925817/78187789-72742080-7445-11ea-82f3-3d56b94fec12.png)

## Cards

https://trello.com/c/XXDIrY65/32-login

2020-04-01 23:33 UTC, eledwinn requested changes

2020-04-01 23:33 UTC, eledwinn commented on login.html
> +<div class="login-inputs">
Please indent all file :D

2020-04-01 23:33 UTC, eledwinn commented on login.html
> +</html>
Remember empty line at EOF

2020-04-01 23:33 UTC, eledwinn commented on login.html
> +                <input class="form-input" type="text" id="email" name="email"><br><br>
Avoid to use <br> for split controls... Use margin
For this, try insert each label and input into a div

2020-04-01 23:33 UTC, eledwinn commented on login.html
> +                <button class="form-button-singup" type="submit">Sing Up</button>
Only one button should be type="submit".

2020-04-01 23:33 UTC, eledwinn commented on scss/detail.scss
> +    width: 252px;
Try don't repeat `width` property, this should use same that button.

2020-04-01 23:33 UTC, eledwinn commented on scss/detail.scss
> +}
Try don't repeat same properties for both buttons. Props such as height, width, border-radius can join.

2020-04-01 23:33 UTC, eledwinn commented on scss/detail.scss
> +}
Insert empty line here

2020-04-02 00:06 UTC, CrisVega08 requested changes

2020-04-02 00:06 UTC, CrisVega08 commented on login.html
> +    <img class="logo-wolox-login" src="images/LogoWolox-Original.png" alt= "Wolox Logotype">
```suggestion
    <img class="logo-wolox-login" src="images/LogoWolox-Original.png" alt= "Wolox Logotype" />
```

2020-04-02 00:06 UTC, CrisVega08 commented on login.html
> +            <form class="form-login" action="/index.html" id="form-login">
check indentation

2020-04-02 00:06 UTC, CrisVega08 commented on login.html
> +                <input class="form-input" type="text" id="email" name="email"><br><br>
```suggestion
                <input class="form-input" type="text" id="email" name="email">
```

2020-04-02 00:06 UTC, CrisVega08 commented on scss/detail.scss
> +    display: flex;
Why display flex ?

2020-04-02 00:06 UTC, CrisVega08 commented on scss/detail.scss
> +    position: relative;
Use position relative to .form-button-login no viewport

2020-04-02 00:06 UTC, CrisVega08 commented on scss/detail.scss
> +  width: 252px;
you use a lot this value use on principal container and for other use with relative to this.

2020-04-06 17:52 UTC, CrisVega08 requested changes

2020-04-06 17:52 UTC, CrisVega08 commented on scss/detail.scss
> +  margin: 25px 0 25px 0;
```suggestion
  margin: 25px 0;
```

2020-04-06 17:52 UTC, CrisVega08 commented on scss/detail.scss
> +  margin: 20px 0 10px 0;
```suggestion
  margin: 20px 0 10px;
```

2020-04-06 17:52 UTC, CrisVega08 commented on login.html
> +        <form class="form-login" action="/index.html" id="form-login">
I remember a edwin's comment  about use a div something like:

```
<div class="form-group">
  <label class="form-label" for="email">Email</label>
  <input class="default-rectangle form-input" type="text" id="email" name="email">
</div>

2020-04-06 18:04 UTC, eledwinn requested changes

2020-04-06 18:04 UTC, eledwinn commented on login.html
> +          <input class="default-rectangle form-input" type="text" id="email" name="email">
Remember close inline tags with `/>`

2020-04-06 18:04 UTC, eledwinn commented on login.html
> +          <button class="default-rectangle form-button-singup">Sing Up</button>
Buttons without `type` attribute have `submit` by default. Please always add `type="button"` or `type="submit"`

2020-04-06 18:04 UTC, eledwinn commented on scss/detail.scss
> +  width: 252px;
I think the inputs should not be fixed width. Always try to use relative measures for the contents.
For example, if you change the width of the login box, will you also have to change the width of the inputs.

2020-04-07 12:20 UTC, CrisVega08 commented on login.html
> +</html>
Add empty line

2020-04-07 12:20 UTC, CrisVega08 commented on login.html
> +
delete it

2020-04-07 12:20 UTC, CrisVega08 commented on scss/detail.scss
> +  flex: 1;
```
flex: 1 equals = 
    flex-grow: 1;
    flex-shrink: 1;
    flex-basis: 0%;
```
So delete unnecessary property.

2020-04-07 12:52 UTC, eledwinn approved these changes

2020-04-07 16:54 UTC, CrisVega08 approved these changes

2020-04-07 17:52 UTC, merged