Add responsive for book details
wolox-training/jg-angular pull request #11
Opened 2020-04-07 21:35 UTC by JuanGutierrez43

## Summary 

This will add the responsive feature for adapt the book details for screens under 1024px, for this I had to change some margins, some heights and widths for the logo and the badge. Also, the badge needed to be 30% smaller than the original. So I made use of the CSS variables, and made that with the responsive, the badge image only is going to be a 70% of the original badge. (70/100)*total = 70% of the total. That's the way I used to make the badge adapt to the 30%. 

I fixed some useless margins and paddings too.

**New features**

- Add responsive feature
- Set all the detail with flex, variables, and responsive to be clear at a resolution under 1024px

## Screenshots 

![Screenshot from 2020-04-07 18-25-34](https://user-images.githubusercontent.com/29925817/78721461-faeb3900-78fd-11ea-9813-8db71ae34f53.png)

## Cards

https://trello.com/c/cJS7fUnd/34-responsive

2020-04-07 23:01 UTC, eledwinn requested changes
Great work !!! 👏👏👏

2020-04-07 23:01 UTC, eledwinn commented on scss/detail.scss
> +$badge-mobile-width: calc(#{$book-badge-width} * (70/100));
It's okay to use 0.7, personally I prefer it. @CrisVega08 what do you think?

2020-04-07 23:01 UTC, eledwinn commented on scss/detail.scss
> +
Remove this empty line!!

2020-04-07 23:01 UTC, eledwinn commented on scss/detail.scss
> +    width: 336px;
335px works for you?

2020-04-07 23:51 UTC, CrisVega08 requested changes

2020-04-07 23:51 UTC, CrisVega08 commented on scss/detail.scss
> +$badge-mobile-width: calc(#{$book-badge-width} * (70/100));
I agree and also I think is unnecessary create for mobile variables because you only use once, so in mobile style you can put it directly.

2020-04-07 23:51 UTC, CrisVega08 commented on scss/detail.scss
> +    background-size: 100%;
You can define background-size in shorthand (top-line)

2020-04-13 15:32 UTC, CrisVega08 approved these changes

2020-04-13 15:32 UTC, CrisVega08 commented on scss/detail.scss
> +    width: 335px;
sort properties

2020-04-13 15:32 UTC, CrisVega08 commented on scss/detail.scss
> +    margin: 15px 0 0;
Sort properties

2020-04-13 15:45 UTC, eledwinn approved these changes

2020-04-13 15:57 UTC, merged