Add css grid layout to the book details
wolox-training/jg-angular pull request #13
Opened 2020-04-16 19:01 UTC by JuanGutierrez43

## Summary 

This will add the redesign of the web page with the use of the CSS grid. For this feature I used grid areas to set the divs in the same way that the invision model. 

(I recreated this card because when I merged with master my divs just died. So I needed to delete the branch and start this feature from 0.)

**New features**

- Add grid for the book details
- Removed flex use where I implemented the grid. 
- Add new desing for book details with grid. 
- Add new mobile design for book details using grid too.
- Fixed some divs with problems on the use of the grid. 
- Fixed some margin problems. 

## Screenshots 
![Screenshot from 2020-04-16 13-55-34](https://user-images.githubusercontent.com/29925817/79495558-27d4d580-7ffb-11ea-8014-8080468250c9.png)
![Screenshot from 2020-04-16 13-55-46](https://user-images.githubusercontent.com/29925817/79495560-29060280-7ffb-11ea-9ebd-8108fe6a3c39.png)

## Cards

https://trello.com/c/ftRTatey/12-redise%C3%B1o-de-la-p%C3%A1gina

2020-04-16 19:56 UTC, eledwinn requested changes

2020-04-16 19:56 UTC, eledwinn commented on scss/detail.scss
> +    "area3 area4";
Please add semantic names to areas, like `book-image`, `title`, etc. try use same or similar class name.

2020-04-16 19:56 UTC, eledwinn commented on scss/detail.scss
> +.book-img-container{
```suggestion
.book-img-container {
```

2020-04-17 17:11 UTC, CrisVega08 requested changes

2020-04-17 17:11 UTC, CrisVega08 commented on scss/detail.scss
> +  width: 853px;
```suggestion
  width: 855px.  o. width: 850px. ;
```

2020-04-17 17:11 UTC, CrisVega08 commented on scss/detail.scss
> +  height: 569px;
```suggestion
  height: 570px;
```

2020-04-17 17:11 UTC, CrisVega08 commented on scss/detail.scss
> +  grid-area: area2;
Same comment of edwin

2020-04-17 17:11 UTC, CrisVega08 commented on scss/detail.scss
> +  grid-area: area3;
Same

2020-04-17 17:11 UTC, CrisVega08 commented on scss/detail.scss
> +  grid-area: area1;
Same

2020-04-17 17:11 UTC, CrisVega08 commented on scss/detail.scss
> +  grid-area: area4;
Same

2020-04-17 17:11 UTC, CrisVega08 commented on scss/detail.scss
> +      "area1 area1"
same

2020-04-17 17:11 UTC, CrisVega08 commented on scss/detail.scss
> +      top: 60px;
sort properties

2020-04-17 23:05 UTC, eledwinn approved these changes

2020-04-22 14:50 UTC, CrisVega08 approved these changes

2020-04-22 14:59 UTC, merged