Add login view and ng content for layouts
wolox-training/jg-angular pull request #15
Opened 2020-05-04 21:17 UTC by JuanGutierrez43

## Summary 

There was a needed to use a ng-content for the use of the register and login layouts, so I created the layouts component, to use the ng-content over there. Also, I created the login view for this

This is only the use of the ng-content and the view for the login. In the nexts PRs I will create the feature to switch between classes, and change between the login and registrer. 

**New features**

- Login view 
- Use of <ng-content> for the new component 
- New component (layouts) Layouts will manage the both components of the index, the login and the registrer

## Screenshots 
![Screenshot from 2020-05-04 18-14-15](https://user-images.githubusercontent.com/29925817/81014563-7378e300-8e33-11ea-837c-5fa5d5a5b3a5.png)

## Cards

https://trello.com/c/DaGvB9Qq/21-ngcontent

2020-05-04 21:45 UTC, eledwinn requested changes

2020-05-04 21:45 UTC, eledwinn commented on wolox-books/src/app/app.component.html
> +<app-register-layout></app-register-layout>
Add empty line here please 😄

2020-05-04 21:45 UTC, eledwinn commented on wolox-books/src/app/login-layout/login-layout.component.ts
> +      type: 'text',
Did you mean `type: 'password'`?

2020-05-04 21:50 UTC, CrisVega08 requested changes

2020-05-04 21:50 UTC, CrisVega08 commented on wolox-books/src/app/layouts/layouts.component.html
> +    <div class="layout-inputs">
check indentation

2020-05-04 21:50 UTC, CrisVega08 commented on wolox-books/src/app/layouts/layouts.component.spec.ts
> +import { async, ComponentFixture, TestBed } from '@angular/core/testing';
delete this file

2020-05-04 21:50 UTC, CrisVega08 commented on wolox-books/src/app/login-layout/login-layout.component.html
> +      <form class="form-layout">
check indentation

2020-05-04 21:50 UTC, CrisVega08 commented on wolox-books/src/app/login-layout/login-layout.component.spec.ts
> +import { async, ComponentFixture, TestBed } from '@angular/core/testing';
delete

2020-05-04 21:50 UTC, CrisVega08 commented on wolox-books/src/app/login-layout/login-layout.component.ts
> +  fields = [
move a constants.ts file

2020-05-04 21:50 UTC, CrisVega08 commented on wolox-books/src/app/register-layout/register-layout.component.html
> +      <form class="form-layout">
check indentation

2020-05-04 21:50 UTC, CrisVega08 commented on wolox-books/src/app/register-layout/register-layout.component.html
> +</app-layouts>
add empty line

2020-05-05 22:25 UTC, CrisVega08 approved these changes

2020-05-05 22:25 UTC, CrisVega08 commented on wolox-books/src/app/layouts/layouts.component.html
> +    <img class="logo-wolox-layout" src="../../assets/LogoWolox-Original.png" alt="Wolox Logotype" />
I suggest create a absolute path for assets

2020-05-05 22:35 UTC, eledwinn approved these changes

2020-05-06 17:11 UTC, merged