Add image to the book details
wolox-training/jg-angular pull request #4
Opened 2020-02-28 21:51 UTC by JuanGutierrez43

## Summary 

This will add the new image for the books using flex. Also I added a little fixes in the indentation, and the usage of the classes. Some classes were useless or needed to be updated.

## Screenshots 
![Screenshot from 2020-02-28 18-47-40](https://user-images.githubusercontent.com/29925817/75589951-f019ca80-5a5a-11ea-82cf-c01547d3cca0.png)

## Cards

https://trello.com/c/wHsGRZ43/27-detalle-de-libro-ii-imagen

2020-03-02 15:40 UTC, CrisVega08 requested changes

2020-03-02 15:40 UTC, CrisVega08 commented on index.html
> +          <div class="book-content-row">
check indentation

2020-03-02 15:40 UTC, CrisVega08 commented on index.html
> +  <div class = book-cover-page>
```suggestion
  <div class=book-cover-page>
```

2020-03-02 15:40 UTC, CrisVega08 commented on index.html
> +    <img class = book-img src="images/book-cover.png" alt="Book Cover">
```suggestion
    <img class=book-img src="images/book-cover.png" alt="Book-Cover">
```

2020-03-02 15:40 UTC, CrisVega08 commented on scss/detail.scss
> +  flex-direction: row;
This is default value so you don't need it

2020-03-02 15:52 UTC, eledwinn requested changes

2020-03-02 15:52 UTC, eledwinn commented on index.html
> +  <div class = book-cover-page>
```suggestion
  <div class="book-cover-page">
```

2020-03-02 15:52 UTC, eledwinn commented on scss/detail.scss
>    font-family: Roboto
Please add `;` at end of line.

2020-03-03 19:40 UTC, eledwinn approved these changes

2020-03-03 21:24 UTC, CrisVega08 approved these changes

2020-03-03 21:25 UTC, merged