Add border between book title and book info (Book details part 3)
wolox-training/jg-angular pull request #5
Opened 2020-03-03 21:36 UTC by JuanGutierrez43

## Summary 

This will add the border between the title and the book info to be the presentation more fresh and more structured. For this I used the rectangle image from the invision, and flex to set it on the page.

## Screenshots 
![Screenshot from 2020-03-03 18-35-50](https://user-images.githubusercontent.com/29925817/75821942-ddb2d000-5d7d-11ea-9602-516b5c471422.png)

## Cards

https://trello.com/c/kQ206RUk/28-detalle-de-libro-iii-estructura

2020-03-04 17:00 UTC, eledwinn requested changes

2020-03-04 17:00 UTC, eledwinn commented on index.html
> +      <img class="rectangle" src="images/rectangle.png" alt="Title Border">
You can to use border instead image, avoid to use html elements as decorative details as borders, shadows, etc.

2020-03-04 17:27 UTC, CrisVega08 requested changes

2020-03-04 17:27 UTC, CrisVega08 commented on scss/detail.scss
> +.rectangle {
I am agree with edwin comment so change it and delete this style.

2020-03-04 19:52 UTC, eledwinn requested changes
Please add shadow in the card.

2020-03-04 19:52 UTC, eledwinn commented on scss/detail.scss
> +  width: 550px;
Is this width necessary?

2020-03-05 13:24 UTC, CrisVega08 requested changes

2020-03-05 13:24 UTC, CrisVega08 commented on scss/detail.scss
> +  box-shadow: 4px 4px 10px 0 rgba(0,0,0,0.5);
create a variable on colors for this.

2020-03-05 13:24 UTC, CrisVega08 commented on scss/detail.scss
> +}
Add empty line

2020-03-05 13:24 UTC, CrisVega08 commented on scss/detail.scss
> +//div super gigante que englobe al cover-page
English please

2020-03-05 14:17 UTC, eledwinn approved these changes

2020-03-05 14:23 UTC, CrisVega08 approved these changes

2020-03-05 14:26 UTC, merged