Add badge image to the book details (Book details part 4)
wolox-training/jg-angular pull request #6
Opened 2020-03-05 14:32 UTC by JuanGutierrez43

## Summary 

This will add the badge image and set it in the top right corner of the book image. For this, I used transform to rotate the image like the card and then position to set it all over the book image. 

**New features**

- Add image badge.png
- Set the image over the book image using transform and position.

## Screenshots 
![Screenshot from 2020-03-05 11-27-54](https://user-images.githubusercontent.com/29925817/75991142-c9cdb200-5ed4-11ea-9c5d-5dabe823885c.png)

## Cards

https://trello.com/c/keek9FQ9/29-detalle-de-libro-iv-badge

2020-03-05 14:41 UTC, eledwinn requested changes

2020-03-05 14:41 UTC, eledwinn commented on index.html
> +    <img class="book-badge" src="images/badge.png" alt="Book Badge">
Please, use pseudo-elements to add decorative elements.

2020-03-05 14:41 UTC, eledwinn commented on scss/detail.scss
> +    transform: rotate(1deg);
Cool!!!

2020-03-05 14:53 UTC, CrisVega08 requested changes

2020-03-05 14:53 UTC, CrisVega08 commented on scss/detail.scss
> +.book-badge {
When you use pseudo element this class disappear

2020-03-05 20:16 UTC, eledwinn requested changes

2020-03-05 20:16 UTC, eledwinn commented on scss/detail.scss
> +  content: "";
Please use single quotes 😄

2020-03-05 20:16 UTC, eledwinn commented on scss/detail.scss
> +  width: 100px;
and sort props :P

2020-03-09 14:30 UTC, eledwinn approved these changes

2020-03-19 20:48 UTC, CrisVega08 approved these changes

2020-03-19 20:48 UTC, CrisVega08 commented on scss/detail.scss
> +.book-cover-page::after {
nice but you can made pseudo element inside of book-cover-page something like:
`
.book-cover-page {
  background-color: $white;
  box-shadow: 4px 4px 10px 0 $black-shadow;
  display: flex;
  height: 416px;
  margin: 50px 0 0 50px;
  width: 900px;

  &::after {
    background: url('images/badge.png') no-repeat;
    content: '';
    height: 120px;
    left: 250px;
    position: absolute;
    top: 50px;
    transform: rotate(1deg);
    width: 100px;
  }
}
`

2020-03-20 18:21 UTC, merged