Add book lists
wolox-training/jg-angular pull request #7
Opened 2020-03-20 18:31 UTC by JuanGutierrez43

## Summary 

This will add the book list feature. In this feature, the books where listed in the new view "index.html" and the book details are in other view called "book-details.html" 

**New features**

- Add book list in a new view
- Add book-details in other view
- Set all the list using flex and all the book-list images too. 
- In the list, all the books will redirect to the book details

## Screenshots 
![Screenshot from 2020-03-20 15-22-53](https://user-images.githubusercontent.com/29925817/77194995-af442d00-6abf-11ea-8db8-56cfb27d1e72.png)

## Cards

https://trello.com/c/YIy3Jqpb/30-listado-de-libros

2020-03-20 19:14 UTC, eledwinn approved these changes

2020-03-20 19:14 UTC, eledwinn commented on scss/detail.scss
>    }
Ident please!!!

2020-03-20 19:24 UTC, CrisVega08 requested changes

2020-03-20 19:24 UTC, CrisVega08 commented on scss/detail.scss
> +  margin: 25px 25px 10px 25px;
```suggestion
  margin: 25px 25px 10px;
```

2020-03-20 19:24 UTC, CrisVega08 commented on index.html
> +            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover">
```suggestion
            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover" />
```

2020-03-20 19:24 UTC, CrisVega08 commented on index.html
> +            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover">
```suggestion
            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover" />
```

2020-03-20 19:24 UTC, CrisVega08 commented on index.html
> +            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover">
```suggestion
            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover" />
```

2020-03-20 19:24 UTC, CrisVega08 commented on index.html
> +            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover">
```suggestion
            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover" />
```

2020-03-20 19:24 UTC, CrisVega08 commented on index.html
> +            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover">
```suggestion
            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover" />
```

2020-03-20 19:24 UTC, CrisVega08 commented on index.html
> +            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover">
```suggestion
            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover" />
```

2020-03-20 19:24 UTC, CrisVega08 commented on index.html
> +            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover">
```suggestion
            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover" />
```

2020-03-20 19:24 UTC, CrisVega08 commented on index.html
> +            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover">
```suggestion
            <img class="book-list-img" src="images/book-cover.png" alt="Book Cover" />
```

2020-03-20 19:24 UTC, CrisVega08 commented on scss/detail.scss
> +  width: 198px;
```suggestion
  width: 200px;
```

2020-03-20 19:24 UTC, CrisVega08 commented on scss/detail.scss
> +  width: 142px;
```suggestion
  width: 140px;
```

2020-03-25 18:12 UTC, CrisVega08 approved these changes

2020-03-25 19:46 UTC, merged